server:
  port: 5555

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/hotel_db
    username: root
    password: root

  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: authentication-api
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}

        - id: property-service
          uri: lb://PROPERTYSERVICE
          predicates:
            - Path=/api/v1/property/**

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/